### ISSUE TITLE
Require php_curl

### ISSUE THREAD

**Issue by gregelin** [GovReady/GovReady-WordPress-Agent#18]
Received a rather silent error when trying to follow plugin instructions and visit Govready site.

Seems php_curl was not enabled on a droplet I was using to test.

Found the following error in `/var/log/apache2/error.log`:

```
[Sun Apr 24 15:31:43.775932 2016] [:error] [pid 1786] [client 71.246.251.100:63353] PHP Fatal error:  Call to undefined function Govready\\curl_init() in /var/www/html/wp-content/plugins/GovReady-WordPress-Agent-master/govready.php on line 81, referer: http://wp1.govready.com/wp-admin/admin.php?page=govready
```

**Comment by gregelin** [comment]
On Ubuntu, I needed to run the following as root, including server reboot. Then error was corrected.

```
apt-get update
apt-get install php5-curl
reboot
```

**Comment by jlyon** [comment]
Yep, sorry we need to document this. 

We also have a comment in there to possibly support HTTP_request in addition to Curl (https://pear.php.net/manual/en/package.http.http-request.intro.php), but after looking into it more, it looks like HTTP_request is just a wrapper for CURL, so we wouldn't gain any additional ease of adoption with it http://stackoverflow.com/questions/869927/php-difference-between-curl-and-httprequest.

**Comment by jlyon** [comment]
I added a requirements section to the README.  http://www.tomjepson.co.uk/enabling-curl-in-php-php-ini-wamp-xamp-ubuntu/.

I also added a check that will display a warning message in WordPress if cURL isn't enabled.

![screenshot from 2016-04-27 12 44 34](https://cloud.githubusercontent.com/assets/550909/14865903/d3858f58-0c75-11e6-97b6-f5bb33444eb9.png)
