### ISSUE TITLE
Add encryption

### ISSUE THREAD

**Issue by jlyon** [GovReady/GovReady-WordPress-Agent#39]
I tested this locally, and it was easy as enabling mongoose-encryption, creating keys (see ) and adding them to .env, and changing the require statements. I didn't do a thorough bug test, but didn't notice any issues. I think we could just encrypt everything, but I think the must-encrypt models are
- site
- contact
- measure
- submission 
- user

**Comment by gregelin** [comment]
I think encrypt everything.

**Comment by aschmoe** [comment]
OK, I will try this out today.

**Comment by aschmoe** [comment]
@gregelin got the encrypted mongodb going for plugin.govready.com

Only obvious drawback I can see so far is a hit to performance of the api calls.... its not insane but clearly slower.  I think we can probably optimize to some degree (ex: encrypt key fields on each model) but the lag is definitely concerning.

Perhaps we need to look into other solutions.
