### ISSUE TITLE
Failure to install plugin in WordPress

### ISSUE THREAD

**Issue by gregelin** [GovReady/GovReady-WordPress-Agent#51]
Tried to install plugin and it failed.

<img width="1440" alt="screen shot 2016-11-04 at 10 01 07 pm" src="https://cloud.githubusercontent.com/assets/24979/20026879/7e4a5b12-a2da-11e6-8cd7-f7b13b960ec9.png">

**Comment by jlyon** [comment]
Yes, Alex is working on restructuring the WordPress and Drupal plugins to
work with all of the client changes. This should be done next Monday.

**Comment by jlyon** [comment]
Related to #53. Marking as duplicate
